# Generated by Django 3.2.4 on 2021-08-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='show_schedule_on_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
