# Generated by Django 3.2.4 on 2021-08-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_show_schedule_on_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='show_schedule_on_calendar',
            field=models.BooleanField(default=False, verbose_name='Show Schedule on Calendar'),
        ),
    ]
