# Generated by Django 3.2.4 on 2021-08-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetime',
            name='weekday',
            field=models.TextField(default='Sunday', max_length=120),
        ),
    ]
