# Generated by Django 3.2.4 on 2021-08-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursetime_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetime',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
