# Generated by Django 3.2.4 on 2021-08-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursetime_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetime',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='coursetime',
            name='weekday',
            field=models.TextField(default='Sunday', max_length=120, verbose_name='Weekdays'),
        ),
    ]
