# Generated by Django 3.2.4 on 2021-08-25 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20210824_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'user')},
        ),
    ]
