# Generated by Django 3.2.4 on 2021-08-26 00:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20210825_1338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('user', 'name')},
        ),
    ]
