# Generated by Django 3.2.4 on 2021-08-25 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_auto_20210824_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2021, 8, 25, 22, 21, 23, 957176, tzinfo=utc))),
                ('link', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
