# Generated by Django 3.2.4 on 2021-08-25 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homeworkassignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='due_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
