# Generated by Django 3.2.4 on 2021-08-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20210825_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkassignment',
            name='due_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
