# Generated by Django 3.2.4 on 2021-08-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_homeworkassignment_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
