# Generated by Django 3.2.4 on 2021-08-25 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 8, 24))),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
