# Generated by Django 3.2.4 on 2021-08-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_calendar', '0002_alter_calendarevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='time',
            field=models.DateField(blank=True, help_text='Leave Blank if Event is All Day', null=True),
        ),
    ]
