# Generated by Django 3.2.4 on 2021-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_calendar', '0004_calendarevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='time',
            field=models.TimeField(blank=True, help_text='Leave Blank if Event is All Day', null=True),
        ),
    ]
