name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "DJANGO_SETTINGS_MODULE = 'UMSMain.settings.dev'" > os_info.py
    - name: Run Test
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Git Pull
        run: ssh staging "cd /home/ums/UMS-Main && source venv/bin/activate && git pull"

      - name: Django Actions
        run: ssh staging "cd /home/ums/UMS-Main && source venv/bin/activate && pip install -r requirements.txt && python manage.py makemigrations --no-input && python manage.py migrate --no-input && python manage.py collectstatic --no-input"

      - name: Restart the server
        if: ${{ always() }}
        run: ssh staging 'sudo shutdown -r now'
